export const hobbyDescriptions = [
  "Sketching nature scenes in a quiet park",
  "Building model airplanes from vintage kits",
  "Gardening colorful flowers in the backyard",
  "Playing guitar and writing original songs",
  "Baking homemade bread and sweet pastries",
  "Running along scenic forest trails at dawn",
  "Collecting rare coins from around the world",
  "Practicing yoga and mindfulness every morning",
  "Painting landscapes with watercolors on weekends",
  "Writing short stories and poetry in journals",
  "Fishing in lakes during peaceful summer mornings",
  "Hiking mountain trails with friends on weekends",
  "Playing chess at the local coffee shop",
  "Brewing craft beer with unique flavor profiles",
  "Taking wildlife photos on nature photography hikes",
  "Learning calligraphy for wedding invitations and cards",
  "Training in martial arts and self-discipline",
  "Restoring old furniture into modern rustic pieces",
  "Exploring abandoned places and urban ruins",
  "Volunteering at the local animal rescue center",
  "Creating terrariums with moss and tiny figurines",
  "Flying drones and capturing aerial cityscapes",
  "Learning new recipes from international cuisines",
  "Sewing clothes and accessories for cosplay events",
  "Birdwatching in forests with binoculars and guides",
  "Journaling dreams and thoughts each evening",
  "Building custom keyboards from mechanical parts",
  "Homebrewing kombucha with exotic fruit flavors",
  "Dancing salsa at community weekend workshops",
  "Decorating rooms with DIY crafts and lights",
  "Training rescue dogs in basic obedience skills",
  "Composing electronic music on digital software",
  "Rock climbing at the local indoor gym",
  "Practicing digital illustration on a drawing tablet",
  "Knitting scarves and blankets for charity drives",
  "Cycling long-distance trails across the countryside",
  "Watching documentaries and writing personal reviews",
  "Creating origami animals from recycled paper",
  "Tinkering with Raspberry Pi and smart gadgets",
  "Hosting tabletop RPG campaigns for friends",
  "Foraging wild herbs and mushrooms responsibly",
  "Building Lego architecture sets and cityscapes",
  "Editing travel vlogs for a personal YouTube",
  "Decorating cakes with intricate frosting designs",
  "Learning languages using flashcards and apps",
  "Exploring caves and underground tunnels locally",
  "Whittling wood into decorative figurines",
  "Maintaining a saltwater aquarium with exotic fish",
  "Geocaching hidden treasures in the neighborhood",
  "Tattoo designing and sketching intricate patterns"
];
export const names = [
  "Liam", "Emma", "Noah", "Olivia", "Elijah", "Ava", "James", "Sophia", "William", "Isabella",
  "Benjamin", "Mia", "Lucas", "Charlotte", "Henry", "Amelia", "Alexander", "Harper", "Michael", "Evelyn",
  "Daniel", "Abigail", "Matthew", "Ella", "Joseph", "Scarlett", "Jackson", "Emily", "Samuel", "Elizabeth",
  "Sebastian", "Avery", "David", "Sofia", "Carter", "Camila", "Wyatt", "Aria", "Jayden", "Luna",
  "John", "Chloe", "Owen", "Layla", "Dylan", "Mila", "Luke", "Nora", "Gabriel", "Hazel"
];